#!/bin/bash

F77=pgf77
F77FLAGS="-fastsse -mcmodel=medium -Bstatic  -Mextend -pgcpplibs"
INC="/home/vesso/molaris-build/source_official"

MOLARIS_OBJ=" \
process_line.o \
readlib.o \
parmset.o \
read_xyz.o \
killme.o \
fintime.o \
get_code.o \
let2code.o \
typ_to_num.o \
liberr.o \
check_exist_file.o \
check_blank.o \
read_brk.o \
expand_input.o \
trim_to_centroid.o \
trim_to_alpha.o \
check_ang.o \
number_in_lib.o \
find_h.o \
fndchr.o \
fix_resname.o \
fix_atomname.o \
brkerr.o \
lgoodrange.o \
word_count.o \
upper_case.o \
chop_string.o \
help.o \
topoin.o \
check_h_exist.o \
make_alib.o \
chk_nbparm.o \
topology_driver.o \
write_topology.o \
write_sequence.o \
center.o \
create_evb_dat.o \
get_charge_res.o \
getmcphilist.o \
hb_pair.o \
dist.o \
sybyl_lib.o \
connect.o \
addhyd.o \
make_hb.o \
his_h_swich.o \
exclude.o \
bondcode.o \
angcode.o \
torcode_gromos.o \
torcode.o \
itorcode.o \
write_topology_charge.o \
readevblib.o \
def_bond_g.o \
def_bond.o \
def_ang_g.o \
def_ang.o \
puthyd.o \
spray.o \
thrust.o \
get_sp_h.o \
get_wat_h.o \
write_evb.o \
evb_bond.o \
evb_angle.o \
evb_torsion.o \
evb_itorsion.o \
puthydb.o \
elen_for.o \
lcharged_residue.o \
check_env.o \
set_exclude.o \
dist_atoms.o \
find_center.o \
nblist.o \
bondp.o \
thetap.o \
phip.o \
phipsi.o \
nonbond.o \
ephps.o \
exphi.o \
get_xs.o \
enz_default_p.o \
 \
simp_data.o \
task_analyze.o \
electro.o \
header.o \
resatom.o \
allres.o \
restype.o \
resbond.o \
unionres.o \
titration.o \
crgset.o \
ionres.o \
add_sidechain.o \
resang.o \
check_disulfide.o \
check_tor.o \
dock2.o \
grp_contribute.o \
super2.o \
rest_in.o \
genwat.o \
ld_for_membrane.o \
ion_grid_for_membrane.o \
ion_rec_grid_for_membrane.o \
gen_memgrid.o \
buildmem.o \
mutate_res.o \
mutate_h2o.o \
rotate_loh.o \
add_main_atoms.o \
cross_autocorrelation.o \
get_autocorrelation.o \
rotphi.o \
simp_to_expl_relax.o \
refine_parameters.o \
write_vdw.o \
expl_pdb_2_relax.o \
rotate_atom.o \
rotate_helix.o \
sphere.o \
rotate_aix.o \
get_gyration.o \
rms.o \
restor.o \
resitor.o \
system_energy.o \
rest_to_pdb.o \
aa_rest_in.o \
list_hbond.o \
vdwsurf.o \
trajec_langevin_torsion.o \
makepdb.o \
refine_by_qm.o \
makelib1.o \
movie.o \
epotent.o \
update_big.o \
find_key.o \
get_rescen.o \
write_ionizable.o \
get_conf.o \
enz_randm.o \
steepd_min.o \
md_init.o \
trajec.o \
pre_get_e.o \
transform2.o \
vqq_eff_ion3.o \
get_ndir.o \
rotate.o \
update_nonbonded.o \
charge_ion_rec_grid_for_membrane.o \
rotate_wat.o \
rotate_h.o \
trajec_movie.o \
procons.o \
econst.o \
md_parm_defaults.o \
level_get_dgm.o \
keyw_level_evb.o \
pol_parm.o \
enzblkdta.o \
enz_files.o \
gateway.o \
init_x1.o \
trajec_langevin_x.o \
sim_evbatom_to_exp.o \
sim_exp_evb_ts.o \
nbplist.o \
mc_rotate.o \
monte_carlo.o \
rest_in2.o \
get_energy.o \
npwlist.o \
indexing.o \
glossary.o \
write_restart.o \
poly_ene.o \
write_ene.o \
fix_position.o \
random.o \
utilities_topo.o \
write_aminoentry.o \
frame.o \
write_topology_amber.o \
get_line.o \
comment_a.o \
get_line2.o \
check_num_force.o \
ave_atoms_f.o \
get_num_dd.o \
fgapopen.o \
QCP.o \
get_one_fix.o \
neugrp_charge.o \
watcons.o \
central_kill.o \
central_list.o \
hb_count.o \
init_fdft.o \
init_qmmm.o \
init_qcff.o \
charge_clear.o \
rigid_tor_rotation.o \
init_lan.o \
set_pmf_x.o \
write_hamiltonian.o \
randm.o \
comment_n.o \
rest_in3.o \
jacobi.o \
eigsrt.o \
link_x.o \
init_frozen.o \
wpolcons.o \
write_header_test.o \
morzv.o \
thetapv.o \
phipv.o \
nondoub.o \
ave_elecstatic_evb.o \
nondoubv.o \
offdiag.o \
offdiag2.o \
born.o \
vborn.o \
vborn_poly_evb.o \
evb_da_cons.o \
ub_cons_angle.o \
pre_enz.o \
process_keywords.o \
latom_in_region1.o \
keyw_level_pmf.o \
get_cons.o \
md_parm.o \
nqplist.o \
taylor.o \
longpp.o \
longpw.o \
longww.o \
keyw_level_fdft.o \
keyw_level_qm.o \
get_region1_radius.o \
update_frozen.o \
aa_rg1.o \
aa_res.o \
enz_nof.o \
induce.o \
induce_q.o \
born_evb.o \
non_plink.o \
check_hot.o \
nonpoly.o \
genfield.o \
genfieldq.o \
enz_genfldp.o \
born_poly.o \
lquantum_atom.o \
proton_transport.o \
do_rotamer_mc.o \
gen_grid.o \
enz_fun.o \
get_time.o \
expand.o \
nonpoly_gromos.o \
non_central.o \
central_poly.o \
enz_lgvn.o \
watcons_gromos.o \
updDensity.o \
evb_prep.o \
poly_prep.o \
poly_pdld.o \
genwat_gromos.o \
prot_grp.o \
ang_cons.o \
tor_cons.o \
nbpwlist.o \
nqpwlist.o \
read_ablink.o \
picksrt.o \
evb_parm.o \
entropy.o \
link_atom.o \
genfieldp.o \
langevin_qm.o \
evb_sect.o \
stop_qmmm.o \
read_qm_out.o \
aver_qmmm_coor.o \
aver_qmmm_ldcoor.o \
fix_hot_atom.o \
setRDF.o \
prnRDF.o \
write_ave_elec_evb.o \
level_relax.o \
pre_sim_exp_evb_ts.o \
do_rotamer_mc2.o \
tor_steep_mc_res.o \
do_mc_res_mix.o \
do_mc_res.o \
qm_get_forces.o \
enzy.o \
non_qcff_evb.o \
quantum_ind.o \
evb_bond_map.o \
get_code2.o \
initRDF.o \
trajec_langevin_chem_conf.o \
trajec_langevin_helicase.o \
trajec_langevin_sol.o \
trajec_gromos.o \
do_min.o \
Jpotmapx.o \
simp_evb.o \
ubsample_r.o \
updat_lgvn.o \
newf_lgvn.o \
mol_dumy.o \
JMINcg.o \
JMINfunx.o \
nld_solvate.o \
nbplist_gromos.o \
genf_lgvn.o \
enz_sci.o \
cal_qmlink_d.o \
get_side_center.o \
lgdpeq.o \
fdft_energy.o \
qcff_energy.o \
qmmm_energy_maciek.o \
qmmm_energy.o \
frozn_energy.o \
prep_qmmm.o \
qmmm_ref_restart.o \
phy_cnst.o \
blockdata.o \

qm_magic.o \
qm_magic_inter.o \
qm_magic_storage.o \
qm_magic_inputparm.o \
"

MOLARIS_OBJ_PATH="/home/vesso/molaris-build/source_official/"

OBJ=" \
pretopq.o \
cg_energetics_mod.o \
energy_e.o"

OBJ_PATH="/home/vesso/monte"

OBJ_LIST=""

for i in ${MOLARIS_OBJ}
do
   OBJ_LIST=${OBJ_LIST}" "${MOLARIS_OBJ_PATH}/$i
done

for i in ${OBJ}
do
   OBJ_LIST=${OBJ_LIST}" "${OBJ_PATH}/$i
done

${F77} ${F77FLAGS} -c pretopq.f -I${INC} ${OBJ_LIST}
${F77} ${F77FLAGS} -c energy_e.f -I${INC} ${OBJ_LIST}
${F77} ${F77FLAGS} -o assemble assemble.f -I${INC} ${OBJ_LIST}
${F77} ${F77FLAGS} -o cg cg.f -I${INC} ${OBJ_LIST}
